
export const jobsData = [
  {
    id: 1,
    title: "Software Engineer",
    company: "Google",
    location: "Bangalore, India",
    type: "fulltime",
    experience: "mid",
    salary: 120000,
    displaySalary: "$100k - $150k / per year",
    description:
      "Design, build, and maintain scalable web applications used by millions of users worldwide.",
    skills: ["JavaScript", "React", "Node.js", "SQL", "Problem Solving"],
    employmentType: "Full-time",
    experienceText: "2 - 5 years",
    postedAt: "3+ weeks ago",
  },
  {
    id: 2,
    title: "Marketing Manager",
    company: "Amazon",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
    location: "Hyderabad, India",
    type: "fulltime",
    experience: "senior",
    salary: 110000,
    displaySalary: "$90k - $130k / per year",
    description:
      "Lead digital and performance marketing campaigns to drive growth for key product lines.",
    skills: ["Marketing Strategy", "SEO", "Analytics", "Communication"],
    employmentType: "Full-time",
    experienceText: "6 - 10 years",
    postedAt: "2 weeks ago",
  },
  {
    id: 3,
    title: "Graphic Designer",
    company: "Adobe",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/4/48/Adobe_Corporate_Logo.png",
    location: "Remote",
    type: "internship",
    experience: "entry",
    salary: 100000,
    displaySalary: "$80k - $120k / per year",
    description:
      "Create visual assets and marketing materials for web and mobile products.",
    skills: ["Figma", "Illustrator", "Photoshop", "Creativity"],
    employmentType: "Internship",
    experienceText: "0 - 1 years",
    postedAt: "1 week ago",
  },
  {
    id: 4,
    title: "Data Scientist",
    company: "Facebook",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg",
    location: "London, UK",
    type: "fulltime",
    experience: "mid",
    salary: 130000,
    displaySalary: "$110k - $140k / per year",
    description:
      "Analyze large datasets to generate insights and build data products for business teams.",
    skills: ["Python", "Machine Learning", "SQL", "Statistics"],
    employmentType: "Full-time",
    experienceText: "3 - 6 years",
    postedAt: "5 days ago",
  },
  {
    id: 5,
    title: "UI/UX Designer",
    company: "Microsoft",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
    location: "Seattle, USA",
    type: "fulltime",
    experience: "entry",
    salary: 95000,
    displaySalary: "$80k - $100k / per year",
    description:
      "Design intuitive and accessible interfaces for web and desktop applications.",
    skills: ["Figma", "Wireframing", "User Research", "Prototyping"],
    employmentType: "Full-time",
    experienceText: "0 - 2 years",
    postedAt: "1 day ago",
  },
  {
    id: 6,
    title: "Backend Developer",
    company: "Netflix",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    location: "Remote",
    type: "fulltime",
    experience: "senior",
    salary: 145000,
    displaySalary: "$130k - $160k / per year",
    description:
      "Build and optimize backend services that power streaming and personalization features.",
    skills: ["Node.js", "Microservices", "Databases", "System Design"],
    employmentType: "Full-time",
    experienceText: "7+ years",
    postedAt: "4 days ago",
  },
  {
    id: 7,
    title: "Product Manager",
    company: "Apple",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    location: "San Francisco, USA",
    type: "fulltime",
    experience: "mid",
    salary: 135000,
    displaySalary: "$120k - $140k / per year",
    description:
      "Define product strategy, manage roadmaps, and coordinate cross‑functional teams.",
    skills: ["Product Strategy", "Roadmapping", "Stakeholder Management"],
    employmentType: "Full-time",
    experienceText: "3 - 6 years",
    postedAt: "3 days ago",
  },
  {
    id: 8,
    title: "QA Engineer",
    company: "Infosys",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/5/5a/Infosys_logo.svg",
    location: "Chennai, India",
    type: "fulltime",
    experience: "entry",
    salary: 85000,
    displaySalary: "$70k - $90k / per year",
    description:
      "Create and execute test plans to ensure the quality and reliability of applications.",
    skills: ["Manual Testing", "Automation", "Selenium", "API Testing"],
    employmentType: "Full-time",
    experienceText: "0 - 2 years",
    postedAt: "6 days ago",
  },
  {
    id: 9,
    title: "Business Analyst",
    company: "Tata Consultancy Services",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tata_Consultancy_Services_Logo.svg",
    location: "Kochi, India",
    type: "fulltime",
    experience: "mid",
    salary: 105000,
    displaySalary: "$90k - $110k / per year",
    description:
      "Gather requirements, analyze business processes, and support solution design.",
    skills: ["Requirements Gathering", "SQL", "Documentation", "Communication"],
    employmentType: "Full-time",
    experienceText: "2 - 5 years",
    postedAt: "1 week ago",
  },
  {
    id: 10,
    title: "DevOps Engineer",
    company: "IBM",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg",
    location: "Pune, India",
    type: "fulltime",
    experience: "senior",
    salary: 125000,
    displaySalary: "$110k - $130k / per year",
    description:
      "Automate deployment pipelines and manage cloud infrastructure for high availability.",
    skills: ["CI/CD", "Docker", "Kubernetes", "Linux"],
    employmentType: "Full-time",
    experienceText: "6+ years",
    postedAt: "2 weeks ago",
  },
  {
    id: 11,
    title: "Frontend Developer",
    company: "Twitter",
    logo:
      "https://upload.wikimedia.org/wikipedia/en/6/60/Twitter_Logo_as_of_2021.svg",
    location: "Remote",
    type: "internship",
    experience: "entry",
    salary: 70000,
    displaySalary: "$60k - $80k / per year",
    description:
      "Implement responsive and performant user interfaces for social media products.",
    skills: ["JavaScript", "React", "HTML", "CSS"],
    employmentType: "Internship",
    experienceText: "0 - 1 years",
    postedAt: "5 days ago",
  },
  {
    id: 12,
    title: "Cloud Architect",
    company: "Oracle",
    logo:
      "https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg",
    location: "Bangalore, India",
    type: "fulltime",
    experience: "senior",
    salary: 150000,
    displaySalary: "$140k - $160k / per year",
    description:
      "Design and oversee cloud architectures for large enterprise customers.",
    skills: ["Cloud Architecture", "OCI/AWS/Azure", "Security", "Networking"],
    employmentType: "Full-time",
    experienceText: "8+ years",
    postedAt: "1 month ago",
  },
];
